#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
{{ if eq .Values.env.TELEGRAF_INPUT_PLUGIN "mqtt_consumer"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqtt-publisher
  name: deployment-mqtt-publisher
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: mqtt-publisher
  template:
    metadata:
      labels:
        app: mqtt-publisher
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: mqtt-publisher
        image: {{ .Values.DOCKER_REGISTRY }}{{ .Values.images.mqtt_publisher_image }}{{ if .Values.images.image_suffix }}-{{ .Values.images.image_suffix }}{{ end }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsUser: {{ $.Values.env.TIMESERIES_UID }}
          runAsGroup: {{ $.Values.env.TIMESERIES_UID }}
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        command: ["python3", "-u", "publisher.py", "--csv", "/windturbine_data.csv"]
        env:
        - name: HOST_IP
          value: "ia-mqtt-broker"
        - name: SECURE_MODE
          value: '{{ .Values.env.SECURE_MODE }}'
        - name: TS_MS_SERVER
          value: "time-series-analytics-microservice"
        - name: TS_MS_PORT
          value: '{{ .Values.config.time_series_analytics_microservice.kapacitor_port }}'
        volumeMounts:
        {{ if eq .Values.env.SECURE_MODE true }}
        - name: certs
          mountPath: /run/secrets/ca_certificate.pem
          subPath: ca_certificate.pem
        - name: certs
          mountPath: /run/secrets/mqtt-publisher_Server_server_certificate.pem
          subPath: mqtt-publisher_Server_server_certificate.pem
        - name: certs
          mountPath: /run/secrets/mqtt-publisher_Server_server_key.pem
          subPath: mqtt-publisher_Server_server_key.pem
        {{ end }}

      volumes:
      {{ if eq .Values.env.SECURE_MODE true }}
      - name: certs
        secret:
          secretName: ts-certs
          items:
          - key: ca_certificate.pem
            path: ca_certificate.pem
          - key: mqtt-publisher_Server_server_certificate.pem
            path: mqtt-publisher_Server_server_certificate.pem
          - key: mqtt-publisher_Server_server_key.pem
            path: mqtt-publisher_Server_server_key.pem
      {{ end }}
{{ end }}
