#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
namespace: ts-wind-turbine-anomaly-app
DOCKER_REGISTRY: ''
imagePullPolicy: Always
env:
  # The INFLUXDB_USERNAME length must be a minimum of 5 characters
  # Do not set INFLUXDB_USERNAME to 'admin'.
  INFLUXDB_USERNAME: 
  
  # The INFLUXDB_PASSWORD length must be a minimum of 10 alphanumeric characters with at least one digit
  # Do not use the following special characters in the INFLUXDB_PASSWORD "~:'+[/@^{%(-"*|,&<`}._=}!>;?#$)\"
  INFLUXDB_PASSWORD:

  # The VISUALIZER_GRAFANA_USER length must be a minimum of 5 characters
  VISUALIZER_GRAFANA_USER: 
  
  # The VISUALIZER_GRAFANA_PASSWORD length must be a minimum of 10 alphanumeric characters with at least one digit
  VISUALIZER_GRAFANA_PASSWORD: 

  # MR_PSQL_PASSWORD length must be a minimum of 10 alphanumeric characters with atleast one digit
  POSTGRES_PASSWORD:
  
  # MR_MINIO_ACCESS_KEY length must be a minimum of 10 alphanumeric characters with atleast one digit
  MINIO_ACCESS_KEY:
  
  # MR_MINIO_SECRET_KEY length must be a minimum of 10 alphanumeric characters with atleast one digit
  MINIO_SECRET_KEY:
  
  HTTP_PROXY: 
  HTTPS_PROXY: 
images:
  # Please provide the suffix for the image version you want to use like rc1, rc2, git hash id etc.
  image_suffix: ""