#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: ts-wind-turbine-anomaly
version: 1.0.0
description: A Helm chart for Predictive Maintenance - Wind Turbine Anomaly Detection Sample App
helmRegistry: ts-wind-turbine-anomaly-registry
chartName: wind-turbine-anomaly-detection-sample-app
chartVersion: 1.0.0
profiles:
- name: default
  valuesFileName: timeseries-wind-turbine-values.yaml
