# Copyright Intel Corporation

namespace: apps
DOCKER_REGISTRY: ''
DOCKER_USERNAME: ''
DOCKER_PASSWORD: ''
imagePullPolicy: Always
storageClassName: manual
num_video_instances: 1
env:
  ENABLE_WEBRTC: "true"
  ENABLE_RTSP: "true"
  # WEBRTC_SIGNALING_SERVER: "http://{{ $.Values.env.HOST_IP }}:31111"
  HOST_IP: localhost
  RTSP_CAMERA_IP: 
  ENABLE_HTTPS_MODE: false
  MIN_LOG_LEVEL: DEBUG
  MINIO_ACCESS_KEY: 
  MINIO_BUCKET_NAME: model-registry
  MINIO_HOSTNAME: mraas-minio
  MINIO_SECRET_KEY: 
  MINIO_SERVER_PORT: "8000"
  MLFLOW_S3_ENDPOINT_URL: http://127.0.0.1:8000
  SERVER_PORT: "8111"
  https_proxy: 
  http_proxy: 
  no_proxy: mraas-minio
  NO_PROXY: mraas-minio
  POSTGRES_USER: postgres
  POSTGRES_DB: model_registry_db
  POSTGRES_PASSWORD: 
  S3_STORAGE_PORT: 30800
  ENABLE_OPEN_TELEMETRY: true
  # OTEL_COLLECTOR_HOST: {{ $.Values.env.HOST_IP }}
  OTEL_COLLECTOR_PORT: 30418
  OTEL_EXPORT_INTERVAL_MILLIS: 5000
  OPCUA_SERVER_IP:
  OPCUA_SERVER_PORT:
  OPCUA_SERVER_USERNAME:
  OPCUA_SERVER_PASSWORD:
privileged_access_required: false
gpu:
  enabled: false
  type: "gpu.intel.com/i915"
  count: 1
webrtcturnserver:
  username:
  password:
images:
  minio: minio/minio:RELEASE.2020-12-12T08-39-07Z
  model_registry: intel/model-registry:1.0.3
config:
  prometheus:
    name: prometheus
    int:
      prometheus_port: "9090"
    ext:
      prometheus_port: "30909"
  otel_collector:
    name: otel-collector
    int:
      otlp_grpc_port: "4317"
      otlp_http_port: "4318"
      otlp_prometheus_endpoint_port: "9464"
    ext:
      otlp_grpc_port: "30417"
      otlp_http_port: "30418"
      otlp_prometheus_endpoint_port: "30464"
  mediamtx:
    name: mediamtx
    int:
      mediamtx_port: "8889"
      mediamtx_sdp_port: "8189"
      mediamtx_api_port: "9997"
    ext:
      mediamtx_port: "31111"
      mediamtx_sdp_port: "31112"
      mediamtx_api_port: "31222"
  coturn:
    name: coturn
    int:
      coturn_tcp_port: "3478"
      coturn_udp_port: "3478"
    ext:
      coturn_tcp_port: "30478"
      coturn_udp_port: "30478"
  dlstreamer_pipeline_server:
    name: dlstreamer-pipeline-server
    int:
      rest_api_port: "8080"
      rtsp_output_port: "8554"
    ext:
      rest_api_port: "30107"
      rtsp_output_port: "30125"
  model_registry:
    name: model-registry
    int:
      port: "8111"
    ext:
      port: "32002"
volumes:
  pipelines:
    name: vol-pipelines
    size: 100Mi
    location: "/home/pipeline-server/pipelines"
    hostpath: "/opt/intel/eii/pipelines"
  models:
    name: vol-models
    size: 500Mi
    location: "/home/pipeline-server/models"
    hostpath: "/opt/intel/eii/models"
