# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  vlm-openvino-serving:
    image: ${REGISTRY:-}vlm-openvino-serving:${TAG:-latest}
    container_name: vlm-openvino-serving
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        no_proxy: ${no_proxy_env},${HOST_IP}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    ports:
      - "${VLM_SERVICE_PORT}:8000"
    ipc: host
    environment:
      no_proxy_env: ${no_proxy_env},${HOST_IP}
      no_proxy: ${no_proxy_env},${HOST_IP}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      VLM_MODEL_NAME: ${VLM_MODEL_NAME}
      VLM_COMPRESSION_WEIGHT_FORMAT: ${VLM_COMPRESSION_WEIGHT_FORMAT}
      VLM_DEVICE: ${VLM_DEVICE}
      VLM_SEED: ${VLM_SEED}
      WORKERS: ${WORKERS:-1}
      HF_ENDPOINT: https://hf-mirror.com
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 40
      start_period: 10s
    networks:
      - default
    volumes:
      - "/home/$USER/.cache/huggingface:/root/.cache/huggingface"
      - ov-models:/app/ov-model

  dataprep-visualdata-milvus:
    image: ${REGISTRY:-}dataprep-visualdata-milvus:${TAG:-latest}
    container_name: dataprep-visualdata-milvus
    ports:
      - "${DATAPREP_SERVICE_PORT}:9990"
    ipc: host
    environment:
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - DEVICE=${DEVICE}
      - HOST_DATA_PATH=${HOST_DATA_PATH}
      - LOCAL_EMBED_MODEL_ID=${LOCAL_EMBED_MODEL_ID}
      - MODEL_DIR=${MODEL_DIR}
      - MILVUS_HOST=${MILVUS_HOST}
      - MILVUS_PORT=${MILVUS_PORT}
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - ${USER_GROUP_ID-1000} 
      - ${VIDEO_GROUP_ID}    
      - ${RENDER_GROUP_ID}    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$DATAPREP_SERVICE_PORT/v1/dataprep/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 30
      start_period: 30s
    networks:
      - default
    volumes:
      - $HOME/.cache/huggingface:/home/user/.cache/huggingface:rw
      - ${MODEL_DIR}:/home/user/models:rw
      - ${HOST_DATA_PATH}:/home/user/data:rw

  retriever-milvus:
    image: ${REGISTRY:-}retriever-milvus:${TAG:-latest}
    container_name: retriever-milvus
    ports:
      - "${RETRIEVER_SERVICE_PORT}:7770"
    ipc: host
    environment:
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - DEVICE=${DEVICE}
      - LOCAL_EMBED_MODEL_ID=${LOCAL_EMBED_MODEL_ID}
      - MODEL_DIR=${MODEL_DIR}
      - MILVUS_HOST=${MILVUS_HOST}
      - MILVUS_PORT=${MILVUS_PORT}
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - ${USER_GROUP_ID-1000} 
      - ${VIDEO_GROUP_ID}    
      - ${RENDER_GROUP_ID}    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$RETRIEVER_SERVICE_PORT/v1/retrieval/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 30
      start_period: 30s
    networks:
      - default
    depends_on:
      - dataprep-visualdata-milvus
    volumes:
      - $HOME/.cache/huggingface:/home/user/.cache/huggingface:rw
      - ${MODEL_DIR}:/home/user/models:rw

  visual-search-qa-app:
    image: ${REGISTRY:-}visual-search-qa-app:${TAG:-latest}
    container_name: visual-search-qa-app
    ports:
      - "${VISUAL_SEARCH_QA_UI_PORT}:17580"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      host_ip: ${host_ip}
      HOST_DATA_PATH: ${HOST_DATA_PATH}
      LOCAL_EMBED_MODEL_ID: ${LOCAL_EMBED_MODEL_ID}
      VLM_MODEL_NAME: ${VLM_MODEL_NAME}
      BACKEND_VQA_BASE_URL: ${BACKEND_VQA_BASE_URL}
      BACKEND_SEARCH_BASE_URL: ${BACKEND_SEARCH_BASE_URL}
      BACKEND_DATAPREP_BASE_URL: ${BACKEND_DATAPREP_BASE_URL}
      DATA_INGEST_WITH_DETECT: ${DATA_INGEST_WITH_DETECT}
      VISUAL_SEARCH_QA_UI_PORT: ${VISUAL_SEARCH_QA_UI_PORT}
      MAX_MAX_NUM_SEARCH_RESULTS: ${MAX_MAX_NUM_SEARCH_RESULTS:-200}
      DEFAULT_NUM_SEARCH_RESULTS: ${DEFAULT_NUM_SEARCH_RESULTS:-10}
      SHOW_RESULT_PER_ROW: ${SHOW_RESULT_PER_ROW:-5}
    restart: unless-stopped  
    healthcheck:
      test: ["CMD-SHELL", "echo 'Health check' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 30
      start_period: 30s
    networks:
      - default
    volumes:
      - ${HOST_DATA_PATH}:/home/user/data:rw

volumes:
  ov-models:
    external: true

networks:
  default:
    driver: bridge